### ISSUE TITLE
can you make deepfacelive use directml or opencl instead of directx12 for non nvidia gpus because that would be more useful then this

### ISSUE THREAD

**Issue by Cxsmo-ai** [idinkov/sd-deepface-1111#1]
can you make deepfacelive use directml or opencl instead of directx12 for non nvidia gpus because that would be more useful then this

**Comment by idinkov** [comment]
I will take a look at that, thanks for the note.

**Comment by idinkov** [comment]
After a more thorough review i will close this, this request concerns the main DeepFaceLive repo in which i have no intentions to modify at this stage. Thanks for the interest though and the idea.

**Comment by Cxsmo-ai** [comment]
i made this request here because you did modify deepfacelive with python 3.10 and stuff but that repo i couldn't make requests.

**Comment by idinkov** [comment]
Yes, i did, but it was a basic adjustment to implement in Stable Diffusion, while the logic stay the same. The improvement you are offering will be a deviation from the idea of this repo.
