### ISSUE TITLE
Can Apple m1 support it

### ISSUE THREAD

**Issue by DeepFace-user** [idinkov/sd-deepface-1111#7]
I would like to know if Mac m1 supports plugins and what does it do? Can live open camera face change live on stable diffusion?

**Comment by idinkov** [comment]
Hello, i am not sure if Mac M1 will support it but you could try. About the second question at the moment the idea is to just replace faces that are generated with stable diffusion with the trained ones you have using the trained .dfl files. Your idea is good and may be implemented in future revisions so you can use your camera to reposition or animate the face.
